// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-section.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/data.ts
var PEOPLE = [
  { name: "Jeremie Landweer", role: "Founder & CEO", group: "leadership" },
  { name: "Dominique Debecker", role: "Chief Behavioural Officer", group: "leadership" },
  { name: "Luc Garguet-Duport", role: "Chief Operating Officer", group: "leadership" },
  { name: "Chris Benardis", role: "Chief Financial Officer", group: "leadership" },
  { name: "Richard Thommeret", role: "External Relations & Strategic Communications", group: "contributors" },
  { name: "Joost Peeters", role: "Legal Advisor", group: "contributors" },
  { name: "Micael Craenhals", role: "Production", group: "contributors" },
  { name: "Karim Tousbih", role: "Value Development", group: "contributors" },
  { name: "Sandrine Helinckx", role: "SBS Foundation", group: "contributors" },
  { name: "Prof. Jan de Visch", role: "SBS Foundation", group: "contributors" },
  { name: "Olivier Begerem", role: "AI & IT Strategy", group: "contributors" },
  { name: "Sarah McArthur", role: "Editor-in-Chief, Leader to Leader Journal", group: "council" },
  { name: "Peter Somers", role: "Former CEO, Emirates Post \xB7 Founder, SprintPack", group: "council" },
  { name: "Tim Sanders", role: "Founder & CEO, Silent Donor", group: "council" },
  { name: "Lars Carlstrom", role: "Founder & CEO, Statetron", group: "council" }
];
var PLACES = [
  { city: "Brussels", country: "Belgium", house: "Corinthia Grand Astoria", stewardship: "Independent", note: "The 64, the founding gathering", wave: "Home", status: "home" },
  { city: "Boom", country: "Belgium", house: "Tomorrowland grounds", stewardship: "With Love Tomorrow", note: "The 300, Shape Tomorrow Today", wave: "Home", status: "home" },
  { city: "London", country: "United Kingdom", house: "The Lanesborough", stewardship: "Oetker Collection", note: "Family owned, capital and culture", wave: "Year One", status: "confirmed" },
  { city: "Cape Town", country: "South Africa", house: "Mount Nelson", stewardship: "Belmond / LVMH", note: "Africa and the Global South", wave: "Year One", status: "confirmed" },
  { city: "Madrid", country: "Spain", house: "", stewardship: "", note: "Europe", wave: "Year One", status: "candidate" },
  { city: "Geneva", country: "Switzerland", house: "Beau-Rivage", stewardship: "Independent, one family since 1865", note: "Institutions and diplomacy", wave: "Year Two", status: "confirmed" },
  { city: "Paris", country: "France", house: "Le Bristol", stewardship: "Oetker Collection", note: "Family owned", wave: "Year Two", status: "confirmed" },
  { city: "New York", country: "United States", house: "The Carlyle", stewardship: "Rosewood, Cheng family", note: "Finance, media, the United Nations", wave: "Year Two", status: "confirmed" },
  { city: "Singapore", country: "Singapore", house: "Capella", stewardship: "Pontiac, Kwee family", note: "The gateway to Asia", wave: "Year Three", status: "confirmed" },
  { city: "Tokyo", country: "Japan", house: "Palace Hotel", stewardship: "Independent, diligence pending", note: "Japan", wave: "Year Three", status: "confirmed" },
  { city: "Mumbai", country: "India", house: "The Taj Mahal Palace", stewardship: "Tata", note: "The largest democracy", wave: "Years Four to Five", status: "confirmed" },
  { city: "Sydney", country: "Australia", house: "Capella", stewardship: "Pontiac, Kwee family", note: "Asia-Pacific anchor", wave: "Years Four to Five", status: "confirmed" },
  { city: "Monaco", country: "Monaco", house: "H\xF4tel de Paris", stewardship: "Monte-Carlo SBM", note: "European depth", wave: "Years Four to Five", status: "confirmed" },
  { city: "Antibes", country: "France", house: "H\xF4tel du Cap-Eden-Roc", stewardship: "Oetker Collection", note: "European depth", wave: "Years Four to Five", status: "confirmed" },
  { city: "Baden-Baden", country: "Germany", house: "Brenners Park-Hotel", stewardship: "Oetker Collection", note: "European depth", wave: "Years Four to Five", status: "confirmed" },
  { city: "Rome", country: "Italy", house: "Orient Express La Minerva", stewardship: "Accor + LVMH", note: "European depth, plus the train", wave: "Years Four to Five", status: "confirmed" },
  { city: "Venice", country: "Italy", house: "Hotel Cipriani", stewardship: "Belmond / LVMH", note: "European depth", wave: "Years Four to Five", status: "confirmed" },
  { city: "Los Angeles", country: "United States", house: "", stewardship: "", note: "North America", wave: "Future wave", status: "candidate" },
  { city: "Mexico City", country: "Mexico", house: "", stewardship: "", note: "North America", wave: "Future wave", status: "candidate" },
  { city: "Buenos Aires", country: "Argentina", house: "", stewardship: "", note: "South America", wave: "Future wave", status: "candidate" },
  { city: "Rio de Janeiro", country: "Brazil", house: "", stewardship: "", note: "South America", wave: "Future wave", status: "candidate" },
  { city: "Marrakech", country: "Morocco", house: "", stewardship: "", note: "North Africa", wave: "Future wave", status: "candidate" },
  { city: "Nairobi", country: "Kenya", house: "", stewardship: "", note: "East Africa", wave: "Future wave", status: "candidate" },
  { city: "Bangkok", country: "Thailand", house: "", stewardship: "", note: "South-East Asia", wave: "Future wave", status: "candidate" },
  { city: "Seoul", country: "South Korea", house: "", stewardship: "", note: "East Asia", wave: "Future wave", status: "candidate" }
];
var EXPERIENCES = [
  {
    slug: "the-64",
    name: "The 64",
    summary: "The founding gathering. Sixty-four individuals in one room, the smallest scale at which the Standard can be set.",
    place: "Brussels, Belgium",
    page: "/the64.html",
    deck: "/the-64-deck.pptx"
  },
  {
    slug: "the-300",
    name: "The 300",
    summary: "Shape Tomorrow Today. Three hundred individuals convened on the Tomorrowland grounds, behaviour in motion at wider scale.",
    place: "Boom, Belgium",
    page: "/the300.html",
    deck: "/the-300-deck.pptx"
  }
];
var SECTIONS = [
  {
    slug: "overview",
    title: "SociisGroup",
    body: "SociisGroup is a sovereign independent benefit corporation based in Brussels, Belgium. It builds behavioural infrastructure for institutions, on the premise that institutions are individuals and institutions are communities, and that outcomes follow behaviour before they follow numbers."
  },
  {
    slug: "impact",
    title: "Sociis Impact",
    body: "SBS and BEE are behavioural infrastructure, not reporting products. The Sustainable Behaviour Standard defines what sustainable behaviour is at the level of the individual and the institution. The Behavioural Engine with Ethics turns that standard into decisions that can be observed, held and repeated."
  },
  {
    slug: "culture",
    title: "Sociis Culture",
    body: "Culture is how SociisGroup reaches one billion individuals for higher sustainability standards. The Rooms gather hundreds. Culture reaches the orders of magnitude the Standard requires. It moves faster than governance and reaches further than boardrooms. Most institutions use culture as marketing. SociisGroup holds every cultural object it produces to the LIME Code that governs the institution itself."
  },
  {
    slug: "lime-code",
    title: "The LIME Code",
    body: "The LIME Code frames inner conduct and the use of power. It governs the institution itself before it is asked of anyone else, and every cultural object, gathering and decision is held to it."
  },
  {
    slug: "governance",
    title: "Governance",
    body: "SociisGroup is governed through a defined institutional structure. Authority, oversight and executive responsibility are intentionally separated to safeguard independence, integrity and long-term trust."
  },
  {
    slug: "house",
    title: "Sociis House",
    body: "Sociis House is behaviour in motion, the environment where the Standard is practised rather than described. It is reached at https://www.sociis.house/."
  },
  {
    slug: "access",
    title: "Access",
    body: "Access is by manual selection, without forms. If the institution resonates, the correspondence address is hello@sociisgroup.com."
  },
  {
    slug: "places",
    title: "Places",
    body: "Home is in Belgium. From there the institution moves across the world, one city at a time, each house a clean, mostly family owned grande dame, one per city, every one screened by the Venue and Place Standard. Houses named are screened candidates, confirmed in writing before any public use."
  }
];

// src/lib/mcp/tools/get-section.ts
var get_section_default = defineTool({
  name: "get_section",
  title: "Get section",
  description: "Read the published institutional text for one section of the SociisGroup site, or list every available section.",
  inputSchema: {
    slug: z.string().optional().describe(
      "Section slug, for example overview, impact, culture, lime-code, governance, house, access, places. Omit to list all sections."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    if (!slug) {
      return {
        content: [
          {
            type: "text",
            text: SECTIONS.map((s) => `${s.slug} \u2014 ${s.title}`).join("\n")
          }
        ],
        structuredContent: { sections: SECTIONS.map(({ slug: s, title }) => ({ slug: s, title })) }
      };
    }
    const key = slug.trim().toLowerCase();
    const section = SECTIONS.find((s) => s.slug === key);
    if (!section) {
      throw new ToolError(
        `Unknown section "${slug}". Available sections: ${SECTIONS.map((s) => s.slug).join(", ")}.`
      );
    }
    return {
      content: [{ type: "text", text: `${section.title}

${section.body}` }],
      structuredContent: { section }
    };
  }
});

// src/lib/mcp/tools/list-experiences.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_experiences_default = defineTool2({
  name: "list_experiences",
  title: "List experiences",
  description: "List SociisGroup's published gatherings, The 64 and The 300, with their place, page and deck links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const text = EXPERIENCES.map(
      (e) => `${e.name} \u2014 ${e.place}
${e.summary}
Page: ${e.page}
Deck: ${e.deck}`
    ).join("\n\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { experiences: EXPERIENCES }
    };
  }
});

// src/lib/mcp/tools/list-governance.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_governance_default = defineTool3({
  name: "list_governance",
  title: "List governance",
  description: "List the people in SociisGroup's published governance structure: the Executive Leadership Team, contributors, and the advisory council.",
  inputSchema: {
    group: z2.enum(["leadership", "contributors", "council", "all"]).default("all").describe("Which part of the governance structure to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ group }) => {
    const people = group === "all" ? PEOPLE : PEOPLE.filter((p) => p.group === group);
    const text = people.map((p) => `${p.name} \u2014 ${p.role} (${p.group})`).join("\n");
    return {
      content: [{ type: "text", text: text || "No people found for that group." }],
      structuredContent: { people }
    };
  }
});

// src/lib/mcp/tools/list-places.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_places_default = defineTool4({
  name: "list_places",
  title: "List places",
  description: "List the cities and houses in SociisGroup's published place map, with stewardship, wave and status. Houses named are screened candidates.",
  inputSchema: {
    status: z3.enum(["home", "confirmed", "candidate", "all"]).default("all").describe("Filter by place status."),
    query: z3.string().optional().describe("Optional case-insensitive match on city, country or house name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status, query }) => {
    const needle = query?.trim().toLowerCase();
    const places = PLACES.filter((p) => status === "all" || p.status === status).filter(
      (p) => needle ? `${p.city} ${p.country} ${p.house}`.toLowerCase().includes(needle) : true
    );
    const text = places.map(
      (p) => `${p.city}, ${p.country} \u2014 ${p.house || "house not yet named"}${p.stewardship ? ` (${p.stewardship})` : ""} \xB7 ${p.wave} \xB7 ${p.status} \xB7 ${p.note}`
    ).join("\n");
    return {
      content: [{ type: "text", text: text || "No places matched that filter." }],
      structuredContent: { places }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sociis-luxury-redesign",
  title: "Sociis Luxury Redesign",
  version: "0.1.0",
  instructions: "Read-only tools for SociisGroup's published institutional record. Use `get_section` for the institutional text (mandate, impact, culture, the LIME Code, governance, access), `list_governance` for the leadership team, contributors and advisory council, `list_places` for the city and house map, and `list_experiences` for The 64 and The 300. All data is already public.",
  tools: [get_section_default, list_governance_default, list_places_default, list_experiences_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
